name: 'olist_dw'
version: '1.0.0'
profile: 'olist_dw'

model-paths: ["models"]

models:
  olist_dw:
    +schema: dw
    stg:
      +materialized: view
    dim:
      +materialized: table
    fact:
      +materialized: table
